### ISSUE TITLE
Failed to decompress large file

### ISSUE THREAD

**Issue by VolMi** [ckolivas/lrzip#16]
I created an archive on 28 July 2011, which I cannot open anymore.

```
$ du -h myLargeArchive.tar.lrz
152G    myLargeArchive.tar.lrz

$ file myLargeArchive.tar.lrz
myLargeArchive.tar.lrz: LRZIP compressed data - version 0.6

$ lrunzip myLargeArchive.tar.lrz
Output filename is: myLargeArchive.tar
Decompressing...
Failed to decompress buffer - lzmaerr=1
Failed to decompress buffer - lzmaerr=1
Failed to decompress in ucompthread
Fatal error - exiting
```

I remember, that, at that time, I did some testing with smaller archives and compression and decompression worked fine.

[Googling around](https://www.google.com/#q=lrzip "Failed to decompress in ucompthread"&tbs=li:1), I found that someone [posted](http://ck-hack.blogspot.de/2012/03/lrzip-0612.html) this error message in your (?) blog, but only concerning very small archives.

I am on Debian Testing, and it occured in Debian's lrzip version 0.608-2. I compiled lrzip-0.614 from http://ck.kolivas.org/apps/lrzip/ but get the same result.

Is there something I can do to about it?

I probably created the archive like this

```
$ tar ... | lrzip -q -L6 -p2 -w5
```

Thanks

**Comment by kryztoval** [comment]
I just got this:
Failed to decompress buffer - bzerr=-4
Failed to decompress in ucompthread

Is this the same error? I used the latest lzr available on 6/25/2015 😢

**Comment by barrykn** [comment]
I think I ran into this issue when trying to decompress several files from (I think) 2008, which I compressed with lrzip 0.19. (I got messages very similar to @VolMi, with the last 5 lines identical.) However, I still had a copy of the lrzip 0.19 binary I compiled in 2008 (for i386 not amd64 because my own Linux boxes were still i386 at that point -- not sure if that's relevant), and that was able to decompress all but one of the files. (The one that failed had some kind of checksum error. Oh well.)

So, for anyone else who runs into this, it might be worth trying an older version of lrzip.

(Perhaps I should try testing some versions between 0.19 and whatever Debian stable is currently shipping, but it might be a while before I get around to it -- to be honest, I expect that most of the industrialized world will be vaccinated against the coronavirus before I get a chance.)

**Comment by pete4abw** [comment]
[Here is an archive going way back](http://ck.kolivas.org/apps/lrzip/). But current versions make accommodations for older archive formats.If you peek at byte 0x5 of the lrzip file, you can see the minor version number.

# Magic Header
Byte|Desc
----|----
0-3|LRZI
4|lrzip major version (always 0 even now)
5|lrzip minor version

From that you can get at what you want. For lrzip files < 0.4x you _may_ need to get the old sources. Code has been added over the years to detect old files and try and decompress them. A suggestion, use `-vv` when trying to figure out what's wrong. Gives a lot more info.

Good luck!

**Comment by barrykn** [comment]
Thanks for the -vv suggestion and the archive link. (It may still be a while before I get around to investigating this further, but I'll try to do it at some point.)
