### ISSUE TITLE
Encryption of existing archive

### ISSUE THREAD

**Issue by acuifex** [ckolivas/lrzip#197]
Hello!
i have compressed a 55 GiB file with missing encryption flag and now i want to add the encryption to it, what are my options?
recompressing the file because of encryption isn't a good option for me

**Comment by ckolivas** [comment]
There isn't a way to encrypt an existing archive I'm afraid. You can only decompress and then recompress it, or compress the compressed file again, using low compression options since it won't really compress any further. I'd suggest encrypting it with some other dedicated tool makes more sense at this stage.
