### ISSUE TITLE
compat: -c,-C options

### ISSUE THREAD

**Issue by pete4abw** [ckolivas/lrzip#39]
While I see merit in trying to make options similar to gzip (and many are already), the idea of having -c and -C is not good IMO. Since we are in development versions, instead of having synonyms for options, maybe in this branch redefine check as just a long option only since it has no parallel in gzip. Until we ever get to version 1.0 (production), we do have some flexibility in option naming, changing. JM2C.

I do like the --fast and --best synonym options.

**Comment by ckolivas** [comment]
I can't see an issue with adding -C since there are so many options not common to gzip/bzip2/xz. Funnily enough, the --fast and --best I'm the least happy with since I'd really like fast to mean lzo compression and best mean zpaq since hardly anyone will adjust levels meaningfully, but then they don't correspond with level changes which is all those commands are aliases for on gzip/bzip2. My aim was simply to provide a way for lrzip to be a drop in replacement for bzip2, though when I first began work on it I never envisioned it as one but it has since evolved to something different.
